name: upscmainsweb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  pdf_text: ^0.5.0
  file_picker: ^5.2.3
  intl: ^0.19.0
  provider: ^6.1.2
  uuid: ^4.5.1

  syncfusion_flutter_pdf: ^20.4.48
  http: ^0.13.6

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.6+1
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.1.0

  path: ^1.8.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
