// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwo16BcFPp_J7Q96MnGzp9OF1kMN_-yc',
    appId: '1:1047947149820:web:2eb5d7441a228f1e787279',
    messagingSenderId: '1047947149820',
    projectId: 'upscmainsweb',
    authDomain: 'upscmainsweb.firebaseapp.com',
    storageBucket: 'upscmainsweb.firebasestorage.app',
    measurementId: 'G-YE3WCNMFZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZMr99cyj38sWMbMMpe3_Z5tUo6h40VS4',
    appId: '1:1047947149820:android:a2ba310cf73bef16787279',
    messagingSenderId: '1047947149820',
    projectId: 'upscmainsweb',
    storageBucket: 'upscmainsweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0r7-LsShL4ylKW9Y0AI5XhDuLfV_6RcU',
    appId: '1:1047947149820:ios:503be7fa2c861d99787279',
    messagingSenderId: '1047947149820',
    projectId: 'upscmainsweb',
    storageBucket: 'upscmainsweb.firebasestorage.app',
    iosBundleId: 'com.example.upscmainsweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0r7-LsShL4ylKW9Y0AI5XhDuLfV_6RcU',
    appId: '1:1047947149820:ios:503be7fa2c861d99787279',
    messagingSenderId: '1047947149820',
    projectId: 'upscmainsweb',
    storageBucket: 'upscmainsweb.firebasestorage.app',
    iosBundleId: 'com.example.upscmainsweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpwo16BcFPp_J7Q96MnGzp9OF1kMN_-yc',
    appId: '1:1047947149820:web:876b01cdd2dcafe6787279',
    messagingSenderId: '1047947149820',
    projectId: 'upscmainsweb',
    authDomain: 'upscmainsweb.firebaseapp.com',
    storageBucket: 'upscmainsweb.firebasestorage.app',
    measurementId: 'G-8YB6TSGTTT',
  );
}
